apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-state
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.backend.state.storageClass }}
  storageClassName: {{ .Values.backend.state.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.state.size }}
